name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync to Hugging Face Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: jbenbudd/adpr-llama
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: gradio 