name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Hugging Face Space
        uses: huggingface/hub-action@v1
        with:
          repo: jbenbudd/adpr-llama
          token: ${{ secrets.HF_TOKEN }} 